# Generated by Django 3.2.23 on 2023-12-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
            ],
        ),
    ]
