# Generated by Django 3.2.23 on 2023-12-14 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hours',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 16, 53, 27, 25376)),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='John Smith', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
